platform :ios, '16.4'
use_frameworks!
inhibit_all_warnings!

install! 'cocoapods', :deterministic_uuids => false, :warn_for_multiple_pod_sources => false, :warn_for_unused_master_specs_repo => false

source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/Devinet_Team/ios-pod-repo.git'

target 'DVNTAlertManager_Example' do
  pod 'DVNTAlertManager', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
