use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/Devinet_Team/ios-pod-repo.git'

target 'DVNTAlertManager_Example' do
  pod 'DVNTAlertManager', :path => '../'
  
end
